apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-backend
spec:
  template:
    spec:
      containers:
      - name: backend
        env:
        - name: MONGO_URI
          value: "mongodb://dev-mongodb-service:27017/taskmanager"
        - name: JWT_SECRET
          value: "mxa365563mox123"
        - name: PORT
          value: "5000"
