apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: taskmanager-mongodb-dev
  namespace: argocd
spec:
  project: default

  source:
    repoURL: https://github.com/magatte365/k8s-cicd-demo.git
    targetRevision: dev
    path: mongodb/k8s/overlays/dev

  destination:
    server: https://10.43.93.119:443  # my-vcluster
    namespace: default

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: false
    syncOptions:
      - CreateNamespace=true
    retry:
      limit: 5
      backoff:
        duration: 5s
        factor: 2
        maxDuration: 3m
