apiVersion: apps/v1
kind: Deployment
metadata:
  name: taskmanager-frontend
  labels:
    app: frontend
    component: taskmanager
spec:
  replicas: 2
  selector:
    matchLabels:
      app: frontend
      component: taskmanager
  template:
    metadata:
      labels:
        app: frontend
        component: taskmanager
    spec:
      containers:
      - name: frontend
        image: magatte2380/taskmanager-frontend:latest
        ports:
        - containerPort: 80
          name: http
        env:
        - name: APP_VERSION
          value: "1.0.0" # APP_VERSION
        - name: BACKEND_URL
          value: "http://backend-service:5000"
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 30
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /
            port: 80
          initialDelaySeconds: 10
          periodSeconds: 5
