apiVersion: v1
kind: Service
metadata:
  name: frontend-service
  labels:
    app: frontend
    component: taskmanager
spec:
  type: NodePort
  selector:
    app: frontend
    component: taskmanager
  ports:
  - port: 80
    targetPort: 80
    protocol: TCP
    name: http
    nodePort: 30001
