apiVersion: apps/v1
kind: Deployment
metadata:
  name: k8s-cicd-demo
  labels:
    app: k8s-cicd-demo
spec:
  replicas: 2
  selector:
    matchLabels:
      app: k8s-cicd-demo
  template:
    metadata:
      labels:
        app: k8s-cicd-demo
    spec:
      containers:
      - name: app
        image: magatte2380/k8s-cicd-demo:dev-689e2d0
        ports:
        - containerPort: 3000
          name: http
        env:
        - name: NODE_ENV
          value: "production"
        - name: APP_VERSION
          value: "689e2d0" # APP_VERSION
        resources:
          requests:
            memory: "128Mi"
            cpu: "100m"
          limits:
            memory: "256Mi"
            cpu: "200m"
        livenessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 10
          periodSeconds: 10
        readinessProbe:
          httpGet:
            path: /health
            port: 3000
          initialDelaySeconds: 5
          periodSeconds: 5
